/*
File Name: analysis.sql
Author: Amaan Faroqui
Date Created: 14-09-2025
Description: This file contains the analysis queries for the Chinook music store database project.
*/


-- Question 1: Find the top 5 customers by total spending.
SELECT
    c.FirstName,
    c.LastName,
    SUM(il.UnitPrice * il.Quantity) AS TotalSpending
FROM
    Customer c
JOIN
    Invoice i ON c.CustomerId = i.CustomerId
JOIN
    InvoiceLine il ON i.InvoiceId = il.InvoiceId
GROUP BY
    c.CustomerId
ORDER BY
    TotalSpending DESC
LIMIT 5;


-- Question 2: Find the best-selling music genre in the USA.
SELECT
    g.Name AS GenreName,
    SUM(il.Quantity) AS TotalTracksSold
FROM
    Genre g
JOIN
    Track t ON g.GenreId = t.GenreId
JOIN
    InvoiceLine il ON t.TrackId = il.TrackId
JOIN
    Invoice i ON il.InvoiceId = i.InvoiceId
WHERE
    i.BillingCountry = 'USA'
GROUP BY
    g.Name
ORDER BY
    TotalTracksSold DESC
LIMIT 1;


-- Question 3: Calculate the total sales generated by each sales support agent.
SELECT
    e.FirstName,
    e.LastName,
    SUM(i.Total) AS TotalSales
FROM
    Employee e
JOIN
    Customer c ON e.EmployeeId = c.SupportRepId
JOIN
    Invoice i ON c.CustomerId = i.CustomerId
WHERE
    e.Title = 'Sales Support Agent'
GROUP BY
    e.EmployeeId
ORDER BY
    TotalSales DESC;